
module.exports = function(grunt) {

  // Project configuration.
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    // ----------------------------
    // option for LESS compiler
    // ----------------------------
    less : {
      options : {
        banner: '/* Auto generated by LESS compiler.  Do not modify!  */ \n'
      },
      src: {
        expand: true,
        cwd: './',
        src: [
          'app/css/**/*.less'
        ],
        dest: './',
        ext: '.css'
      }
    },

    watch: {
      files:
          [
              //
              // Watch for changes of LESS files
              //
              './app/css/**/*.less',
              "./app/test.less"
          ],

	  tasks: [ 'less' ]
    }
  });

  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-less');

  // Default task(s) to run when we type 'grunt'
  grunt.registerTask('default', ['watch', 'less' ]);
  
};